name: Build APKs for pre release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: 'gradle'

      - name: Accept SDK licenses
        run: yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Setup signing configs
        run: |
          echo "$KEYSTORE" | base64 --decode > test.jks
          echo "$KEYSTORE_PROPERTIES" > keystore.properties
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}

      - name: Get date-time string
        id: datetime
        run: |
          DATE_TAG=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "date_tag=$DATE_TAG" >> $GITHUB_ENV

      - name: Build core userdebug APK
        run: ./gradlew assembleCoreUserdebug

      - name: Resolve ffmpeg libs
        run: git clone https://github.com/mikooomich/ffmpeg-android-maker-prebuilt/ -b audio ffMetadataEx/ffmpeg-android-maker

      - name: Build full userdebug APK
        run: ./gradlew assembleFullUserdebug

      - name: Create github userdebug draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ env.date_tag }}
          name: "Build ${{ env.date_tag }}"
          draft: true
          files: |
            app/build/outputs/apk/core/userdebug/*.apk
            app/build/outputs/apk/full/userdebug/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.REL_TOKEN }}
