[versions]
aboutLibraries = "12.2.4"
adaptive = "1.2.0"
androidGradlePlugin = "8.11.1"
annotation = "1.9.1"
kotlin = "2.2.21"
coil = "3.3.0"
compose = "1.9.4"
lazycolumnscrollbar = "2.2.0"
lifecycle = "2.9.4"
material3 = "1.4.0"
media3 = "1.8.0"
room = "2.8.3"
hilt = "2.57.2"
ktor = "3.3.1"
ksp = "2.3.1"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
error-prone-core = { module = "com.google.errorprone:error_prone_core", version = "2.42.0" }
guava = { group = "com.google.guava", name = "guava", version = "33.5.0-android" }
coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version = "1.10.2" }
concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version = "1.3.0" }

gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
activity = { group = "androidx.activity", name = "activity-compose", version = "1.11.0" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.3.0" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version = "1.1.7" }

# compose
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-animation = { group = "androidx.compose.animation", name = "animation-graphics", version.ref = "compose" }
compose-reorderable = { module = "sh.calvin.reorderable:reorderable", version = "3.0.0" }
compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8" }

# ui
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = 'coil-network-okhttp', version.ref = "coil" }
lazycolumnscrollbar = { group = "com.github.nanihadesuka", name = "LazyColumnScrollbar", version.ref = "lazycolumnscrollbar" }
shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version = "1.3.3" }

# material 3
adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
palette = { group = "androidx.palette", name = "palette", version = "1.0.0" }

# viewmodel
viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

media3 = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-workmanager = { group = "androidx.media3", name = "media3-exoplayer-workmanager", version.ref = "media3" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

apache-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.19.0" }

hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# misc
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
brotli = { group = "org.brotli", name = "dec", version = "0.1.2" }

desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.5" }

junit = { group = "junit", name = "junit", version = "4.13.2" }

newpipe-extractor = { group = "com.github.TeamNewPipe", name = "NewPipeExtractor", version = "d59dc21" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
